### PR TITLE
save under normal attributes instead

### PR DESCRIPTION
**Pull request by deniskin82**
I think it should be under "node.normal"

### CODE REVIEW

**Comment by jgoulah** [comment]
ok sure, I didn't actually test it.  Can you also update the version, and the date in the gemspec, thanks!

**Comment by deniskin82** [comment]
done. Also I have converted some double quoted strings to single quoted.

**Comment by jgoulah** [comment]
@deniskin82 sounds good, I think you still need to push it?

**Comment by deniskin82** [comment]
Going to create another PR

**Pull request closed without merging**
